### ISSUE TITLE
[TODO] Test enhancements for #48

### ISSUE THREAD

**Issue by manuelroemer** [ReqRest/ReqRest#49]
## Tasks

#48 introduced new changes which must be tested before the next release.

- [ ] `HttpContentSerializer.Serialize` has a new `contentType` parameter.
- [ ] `HttpContentDeserializer.Deserialize` has a new `CancellationToken` parameter.
- [ ] `SetContent` has new overloads dealing with a serializer.
- [ ] `SetJsonContent` has several new overloads.
- [ ] `Patch/Put/PostJson` have several new overloads.
- [ ] `JsonHttpContentSerializer` has new constructors.
- [ ] `JsonHttpContentSerializer` has new `JsonSerializer` behavior (it is now settable).

## Additional Information

Some of these are going to be hard to test, e.g. the `CancellationToken` support. It must be evaluated for which of these changes new (explicit) tests should be introduced.
Ideally, all methods are at least **run** once in a test container, even though some parameters like the `CancellationToken` are not explicitly tested.

## Open Questions

_None._

**Comment by LiMeiMei-Cpu** [comment]
this lib so cool ，i like it
